### ISSUE TITLE
SM-G950U Oreo

### ISSUE THREAD

**Issue by radioraheem** [google-ar/WebARonARCore#52] opened 2018-01-23 20:07 UTC
Hi there! 

I installed the ARCore components, when I try to launch WebARonARCore it tells me device is not supported. 

I am on a S8 (SM-G950U) on T-Mobile, running the latest Oreo beta preview from Samsung (direct from them, not sideloaded or flashed).  

Is the presence of Oreo the issue?  Guessing it is but wanted to ask specifically in case anyone else runs into this like I did and finds nothing when searching for help.

Thanks!

**Comment by judax** [comment] 2018-01-24 03:17
Thanks for pointing this out. It is quite strange. Android O should be supported.
Let try to find out what the problem is and for that, would you mind confirming a couple of things first?

1. Have you installed both the WebARonARCore.apk and the ARCore.apk from the links in the README.md of the repo? If you are not sure I would suggest you try it again. Going to the github page using your mobile browser can be the easiest way.
2. What specific version of the Android OS are you testing on? This information should be in Settings.

Thank you.

**Comment by radioraheem** [comment] 2018-01-24 14:29
1.  Yup, installed both straight from the readme.md, used my mobile browser (chrome stable).
2.  Android 8.0.0.  Happy to provide build numbers or other related info if it would be at all useful. 

Thanks for the help!

**Comment by judax** [comment] 2018-02-28 17:58
#57 has landed already. Please, be mindful that the current version of WebARonARCore is not built against the ARCore 1.0 SDK. Still, as the communication bridge between the API and the ARCore service is the same, it seems to be working well. We are working on a major reimplementation of this whole project on top of the latest Chromium and ARCore. ETA still TBD.

**Closed as completed by judax** 2018-02-28 17:58 UTC
